apt update
apt install -y software-properties-common
add-apt-repository -y ppa:deadsnakes/ppa
apt update
DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt install -y python3.9 python3-pip zip
mkdir -p layer/python/lib/python3.9/site-packages
pip3 install requests boto3 bs4 -t layer/python/lib/python3.9/site-packages/
cd layer  
zip -r mypackage.zip *
